export default {
    PICKED_UP: {
        status: 'picked-up',
        comment: null,
        showOnDeliveryModal: 'no',
    },
    DELIVERED: {
        status: 'delivered',
        comment: null,
        action: 'agent-delivered',
        showOnDeliveryModal: 'no',
    },
    RETURNED: {
        status: 'agent-returned',
        comment: null,
        showOnDeliveryModal: 'no',
    },
    RETURN: {
        status: 'agent-returning',
        comment: null,
        failureReason: 'RETURN',
        action: 'exchange-parcel-returned',
        showOnDeliveryModal: 'no',
    },
    NOT_REACHABLE: {
        status: 'agent-hold-returning',
        comment: 'কাস্টমারকে ফোনে পাওয়া যায় নি।',
        failureReason: 'NOT_REACHABLE',
        showOnDeliveryModal: 'yes',
    },
    CUSTOMER_PHONE_SWITCHED_OFF: {
        status: 'agent-hold-returning',
        comment: 'কাস্টমার এর ফোন বন্ধ।',
        failureReason: 'HOLD_FOR_CUSTOMER_PHONE_OFF',
        showOnDeliveryModal: 'yes',
    },
    CUSTOMER_CANNOT_RECIEVE_TODAY: {
        status: 'agent-hold-returning',
        comment: 'কাস্টমার আজ পার্সেলটি নিতে পারবেন না। অন্য দিন নিবেন।',
        failureReason: 'HOLD_PARCEL',
        showOnDeliveryModal: 'yes',
    },
    CUSTOMER_WILL_RECIEVE_WITH_OTHER_PARCEL: {
        status: 'agent-hold-returning',
        comment: 'অন্য পার্সেলের সঙ্গে নিবেন।',
        failureReason: 'HOLD_FOR_DELIVERY_WITH_OTHER_PARCEL',
        showOnDeliveryModal: 'yes',
    },
    CUSTOMER_NOT_PRESENT_ON_ADDRESS: {
        status: 'agent-hold-returning',
        comment: 'কাস্টমার নির্দিষ্ট ঠিকানায় উপস্থিত নেই।',
        failureReason: 'HOLD_FOR_CUSTOMER_NOT_PRESENT_ON_ADDRESS',
        showOnDeliveryModal: 'yes',
    },
    CUSTOMER_OFFICE_CLOSED: {
        status: 'agent-hold-returning',
        comment: 'কাস্টমার এর অফিস বন্ধ।',
        failureReason: 'HOLD_FOR_CUSTOMER_OFFICE_CLOSED',
        showOnDeliveryModal: 'yes',
    },
    MERCHANT_ORDERED_TO_HOLD: {
        status: 'agent-hold-returning',
        comment: 'মার্চেন্ট পার্সেলটি হোল্ড করার নির্দেশনা দিয়েছেন।',
        failureReason: 'HOLD_FOR_MERCHANT_ORDERED_TO_HOLD',
        showOnDeliveryModal: 'yes',
    },
    HOLD_FOR_TRANSACTION_PROBLEM: {
        status: 'agent-hold-returning',
        comment: 'লেনদেন এর ঝামেলার জন্য পার্সেলটি হোল্ড করা হয়েছে।',
        failureReason: 'HOLD_FOR_TRANSACTION_PROBLEM',
        showOnDeliveryModal: 'yes',
    },
    DISLIKE_PRODUCT: {
        status: 'agent-returning',
        comment: 'agent-parcel-returning',
        comment: 'কাস্টমার এর পার্সেলটি পছন্দ হয় নি।',
        failureReason: 'DISLIKE_PRODUCT',
        showOnDeliveryModal: 'yes',
    },
    DEFECTIVE_PRODUCT: {
        status: 'agent-returning',
        action: 'agent-parcel-returning',
        comment: 'পার্সেলটি ত্রুটিপূর্ণ।',
        failureReason: 'DEFECTIVE_PRODUCT',
        showOnDeliveryModal: 'yes',
    },
    DIDNT_ORDER: {
        status: 'agent-returning',
        action: 'agent-parcel-returning',
        comment: 'কাস্টমার কোনো অর্ডার করেনি।',
        failureReason: 'DIDNT_ORDER',
        showOnDeliveryModal: 'yes',
    },
    HOLD_LIMIT_REACHED: {
        status: 'agent-returning',
        action: 'agent-parcel-returning',
        comment: 'হোল্ড এর লিমিট অতিক্রম করছে।',
        failureReason: 'HOLD_LIMIT_REACHED',
        showOnDeliveryModal: 'yes',
    },
    // CANCELLED_BY_CUSTOMER: {
    //     status: 'agent-returning',
    //     action: 'agent-parcel-returning',
    //     comment: 'কাস্টমার অর্ডারটি ক্যানসেল করেছেন।',
    //     failureReason: 'CANCELLED_BY_CUSTOMER',
    //     showOnDeliveryModal: 'yes',
    // },
    RETURN_REQUEST_BY_MERCHANT: {
        status: 'agent-returning',
        action: 'agent-parcel-returning',
        comment: 'মার্চেন্ট প্রোডাক্টটি রিটার্ন করতে বলেছেন।',
        failureReason: 'RETURN_REQUEST_BY_MERCHANT',
        showOnDeliveryModal: 'yes',
    },
    PRICE_ISSUE: {
        status: 'agent-returning',
        action: 'agent-parcel-returning',
        comment: 'লেনদেন এ ঝামেলা আছে।',
        failureReason: 'PRICE_ISSUE',
        showOnDeliveryModal: 'yes',
    },
    AREA_CHANGE: {
        status: 'agent-area-change', // old: agent-hold-returning
        comment: 'পার্সেলটি অন্য এলাকায় যাবে।',
        failureReason: 'AREA_CHANGE',
        showOnDeliveryModal: 'yes',
    },
    WRONG_PRODUCT: {
        status: 'agent-returning',
        action: 'agent-parcel-returning',
        comment: null,
        failureReason: 'WRONG_PRODUCT',
        showOnDeliveryModal: 'no',
    },
    LOST_PRODUCT: {
        status: 'agent-returning',
        action: 'agent-parcel-returning',
        comment: null,
        failureReason: 'LOST_PRODUCT',
        showOnDeliveryModal: 'no',
    },
    OTHERS: {
        status: 'agent-returning',
        action: 'agent-parcel-returning',
        comment: null,
        failureReason: 'OTHERS',
        showOnDeliveryModal: 'no',
    },
};
